CREATE TABLE "05-06 Total Pledges and Donations" (
	"Donor ID" INTEGER,
	"Last Name" VARCHAR(50),
	"Head of Household" VARCHAR(50),
	"Spouse Name" VARCHAR(50),
	Salutation VARCHAR(50),
	"Street Address" VARCHAR(50),
	ZipCode_ID INTEGER,
	"CYP Total Pledged" DECIMAL(15,4),
	"SumOfDonation Amount" DOUBLE
);
CREATE TABLE "CYP 05-06 History from 06-07 table -thru 10/05/06" (
	"Primary Key" INTEGER,
	"Head of Household" VARCHAR(50),
	"Spouse Name" VARCHAR(50),
	"Last Name" VARCHAR(50),
	"CYP Total Pledged" DECIMAL(15,4),
	"CYP Frequency" VARCHAR(50),
	"CYP Pledge" DECIMAL(15,4),
	"YTD Total" DECIMAL(15,4),
	"Dt YTD tot transfrd to Donations" TIMESTAMP,
	"Donation Type" VARCHAR(50),
	"Pledge Balance" DECIMAL(15,4)
);
CREATE TABLE Donations (
	"Donation ID" INTEGER,
	"Donation Amount" INTEGER DEFAULT 0 NOT NULL,
	"Donation Date" TIMESTAMP NOT NULL,
	"Donation Type" VARCHAR(50) NOT NULL,
	"Donor ID" INTEGER DEFAULT 0
);
CREATE TABLE "Donor Student Relationship" (
	"Student ID" INTEGER NOT NULL,
	"Donor ID" INTEGER NOT NULL,
	Relationship VARCHAR(50) DEFAULT '"Parents"'
);
CREATE TABLE "Donor Table" (
	"Donor ID" INTEGER,
	Salutation VARCHAR(50),
	"Head of Household" VARCHAR(50),
	"Spouse Name" VARCHAR(50),
	"Last Name" VARCHAR(50),
	"Street Address" VARCHAR(50),
	ZipCode_ID INTEGER,
	"Primary Phone" VARCHAR(50) DEFAULT '0',
	"Secondary Phone" VARCHAR(50),
	"Primary Email" VARCHAR(50),
	"Secondary Email" VARCHAR(50),
	Classification VARCHAR(50),
	"Phonathon Pledge Type" VARCHAR(50),
	"Phonathon Pledge Amount" DECIMAL(15,4) DEFAULT 0,
	"Please Remove My Name" BIT,
	Comments VARCHAR(255),
	"Primary Key" INTEGER DEFAULT 0,
	"Date Entered" TIMESTAMP,
	"Date Updated" TIMESTAMP,
	Reason VARCHAR(50)
);
CREATE TABLE DormInfo (
	"Dorm/Offcampus" VARCHAR(50),
	ID VARCHAR(50)
);
CREATE TABLE "Month/number" (
	Period VARCHAR(50),
	"Number" INTEGER DEFAULT 0
);
CREATE TABLE "OLD - CYNTHIAs old address book - reference" (
	"Primary Key" INTEGER,
	Confirmation BIT,
	DateUpdate TIMESTAMP,
	Comments VARCHAR(255),
	"Last Name" VARCHAR(50),
	"First Name" VARCHAR(50),
	"Middle Initial" VARCHAR(50),
	"E-mail" VARCHAR(50),
	DormID VARCHAR(255),
	"Room/Apt #" VARCHAR(50),
	Address VARCHAR(50),
	ZipCode_ID INTEGER,
	"Phone, Local" VARCHAR(50),
	"Phone, Mobile" VARCHAR(50),
	"Mother, Last Name" VARCHAR(50),
	"Mother, First Name" VARCHAR(50),
	"Mother, FSU Alum" BIT,
	Mother,email VARCHAR(50),
	"Mother, Address" VARCHAR(50),
	"Mother, City" VARCHAR(50),
	"Mother, State" VARCHAR(50),
	"Mother, Zip lookup" INTEGER DEFAULT 0,
	"Mother, Zip" VARCHAR(50),
	"Mother, Phone" VARCHAR(50),
	"Father, Last Name" VARCHAR(50),
	"Father, First Name" VARCHAR(50),
	"Father, FSU Alum" BIT,
	Father,email VARCHAR(50),
	"Father, Address" VARCHAR(50),
	"Father, City" VARCHAR(50),
	"Father, State" VARCHAR(50),
	"Father, Zip" VARCHAR(50),
	"Father, ZipID" INTEGER DEFAULT 0,
	"Father, Phone" VARCHAR(50),
	"CSU Donor Type" VARCHAR(50),
	"Donor Salutation" VARCHAR(50),
	"New Student" BIT,
	School VARCHAR(50),
	"U Box" INTEGER,
	"Date of Birth" TIMESTAMP,
	"Male/Female" VARCHAR(50),
	Major VARCHAR(50),
	Status_ID INTEGER DEFAULT 0,
	Greek BIT,
	"CSU Alumni" BIT,
	"Graduation Year" VARCHAR(50),
	"CSU Spirit Night" BIT,
	"etc Grads" BIT,
	"CSU Retreat" BIT,
	"Bible Study" BIT,
	Service BIT,
	"Pro-Life March" BIT,
	"Eucharistic Minister" BIT,
	Lector BIT,
	"Altar Server" BIT,
	"Greeter/Usher" BIT,
	"CCD Teacher" BIT,
	Instrument VARCHAR(50),
	Choir BIT,
	"CSU Praise Band" BIT,
	"IM - Flag Football" BIT,
	"IM - Soccer" BIT,
	"IM - Volleyball" BIT,
	"IM - Basketball" BIT,
	"IM - Softball" BIT,
	"Party Planning" BIT,
	Homecoming BIT,
	"CSU Office Help" BIT,
	"Home Parish Name" VARCHAR(50),
	"Home Parish City" VARCHAR(50),
	"Mass - 5:15" BIT,
	"Mass - 8:30" BIT,
	"Mass - 10:00" BIT,
	"Mass - 11:45" BIT,
	"Mass - 6:00" BIT,
	Priest BIT,
	Sister BIT,
	Brother BIT,
	"CYP Total Pledged" DECIMAL(15,4),
	"CYP Frequency" VARCHAR(50),
	"CYP Pledge" DECIMAL(15,4),
	"CYP Gifts to Date" DECIMAL(15,4),
	"CYP Nov" DECIMAL(15,4),
	"CYP Dec" DECIMAL(15,4),
	"CYP Jan" DECIMAL(15,4),
	"CYP Feb" DECIMAL(15,4),
	"CYP Mar" DECIMAL(15,4),
	"CYP Apr" DECIMAL(15,4),
	"CYP May" DECIMAL(15,4),
	"CYP Jun" DECIMAL(15,4),
	"CYP Jul" DECIMAL(15,4),
	"CYP Aug" DECIMAL(15,4),
	"CYP Sep" DECIMAL(15,4),
	"CYP Oct" DECIMAL(15,4),
	"DH Date 1" VARCHAR(50),
	"DH Contribution 1" DECIMAL(15,4),
	"DH Fund 1" VARCHAR(50),
	"DH Date 2" VARCHAR(50),
	"DH Contribution 2" DECIMAL(15,4),
	"DH Fund 2" VARCHAR(50),
	"DH Date 3" VARCHAR(50),
	"DH Contribution 3" DECIMAL(15,4),
	"DH Fund 3" VARCHAR(50),
	"DH Date 4" VARCHAR(50),
	"DH Contribution 4" DECIMAL(15,4),
	"DH Fund 4" VARCHAR(50),
	"DH Date 5" VARCHAR(50),
	"DH Contribution 5" DECIMAL(15,4),
	"DH Fund 5" VARCHAR(50),
	"DH Date 6" VARCHAR(50),
	"DH Contribution 6" DECIMAL(15,4),
	"DH Fund 6" VARCHAR(50),
	"DH Date 7" VARCHAR(50),
	"DH Contribution 7" DECIMAL(15,4),
	"DH Fund 7" VARCHAR(50),
	"DH Date 8" VARCHAR(50),
	"DH Contribution 8" DECIMAL(15,4),
	"DH Fund 8" VARCHAR(50),
	"DH Date 9" VARCHAR(50),
	"DH Contribution 9" DECIMAL(15,4),
	"DH Fund 9" VARCHAR(50),
	"DH Date 10" VARCHAR(50),
	"DH Contribution 10" DECIMAL(15,4),
	"DH Fund 10" VARCHAR(50),
	"DH Date 11" VARCHAR(50),
	"DH Contribution 11" DECIMAL(15,4),
	"DH Fund 11" VARCHAR(50),
	"DH Date 12" VARCHAR(50),
	"DH Contribution 12" DECIMAL(15,4),
	"DH Fund 12" VARCHAR(50),
	"DH Date 13" VARCHAR(50),
	"DH Contribution 13" DECIMAL(15,4),
	"DH Fund 13" VARCHAR(50),
	"DH Date 14" VARCHAR(50),
	"DH Contribution 14" DECIMAL(15,4),
	"DH Fund 14" VARCHAR(50),
	"DH Date 15" VARCHAR(50),
	"DH Contribution 15" DECIMAL(15,4),
	"DH Fund 15" VARCHAR(50),
	"DH Date 16" VARCHAR(50),
	"DH Contribution 16" DECIMAL(15,4),
	"DH Fund 16" VARCHAR(50),
	"DH Date 17" VARCHAR(50),
	"DH Contribution 17" DECIMAL(15,4),
	"DH Fund 17" VARCHAR(50),
	"DH Date 18" VARCHAR(50),
	"DH Contribution 18" DECIMAL(15,4),
	"DH Fund 18" VARCHAR(50),
	"DH Date 19" VARCHAR(50),
	"DH Contribution 19" DECIMAL(15,4),
	"DH Fund 19" VARCHAR(50),
	"DH Date 20" VARCHAR(50),
	"DH Contribution 20" DECIMAL(15,4),
	"DH Fund 20" VARCHAR(50),
	"DH Gifts to Date" DECIMAL(15,4),
	Date_OLD VARCHAR(50),
	"Mother, Permanent Address" BIT,
	"Father, Permanent Address" BIT,
	"OLDClass Year" VARCHAR(50)
);
CREATE TABLE "OLD Zip Code DB - from Download DO NOT USE" (
	ID INTEGER,
	City VARCHAR(28),
	State VARCHAR(2),
	Zip VARCHAR(5)
);
CREATE TABLE "Student Contact Info" (
	"Student ID Number" INTEGER,
	"First Name" VARCHAR(50),
	"Last Name" VARCHAR(50),
	"Middle Initial" VARCHAR(50),
	Email VARCHAR(50),
	DormID VARCHAR(255),
	Sex VARCHAR(50),
	"Room/Apt #" VARCHAR(50),
	"Street Address" VARCHAR(50),
	ZipCode_ID INTEGER,
	"U Box" INTEGER,
	"Phone Local" VARCHAR(50),
	"Phone Mobile" VARCHAR(50),
	"Grade Level" VARCHAR(50),
	School VARCHAR(50),
	"Date of Birth" TIMESTAMP,
	Comments VARCHAR(255),
	"New Student" BIT,
	"Date Entered" TIMESTAMP,
	"Date Updated" TIMESTAMP NOT NULL,
	Reason VARCHAR(50),
	Inactive BIT
);
CREATE TABLE "Student Interest" (
	"Student ID Number" INTEGER DEFAULT 0,
	Confirmation BIT,
	Major VARCHAR(50),
	Greek BIT,
	"CSU Spirit Night" BIT,
	"etc Grads" BIT,
	"CSU Retreat" BIT,
	"Bible Study" BIT,
	Service BIT,
	"Pro-Life March" BIT,
	"Eucharistic Minister" BIT,
	Lector BIT,
	"Altar Server" BIT,
	"Greeter/Usher" BIT,
	"CCD Teacher" BIT,
	Instrument VARCHAR(50),
	Choir BIT,
	"CSU Praise Band" BIT,
	"IM - Flag Football" BIT,
	"IM - Soccer" BIT,
	"IM - Volleyball" BIT,
	"IM - Basketball" BIT,
	"IM - Softball" BIT,
	"Party Planning" BIT,
	Homecoming BIT,
	"CSU Office Help" BIT,
	"Home Parish Name" VARCHAR(50),
	"Home Parish City" VARCHAR(50),
	"Mass - 5:15" BIT,
	"Mass - 8:30" BIT,
	"Mass - 10:00" BIT,
	"Mass - 11:45" BIT,
	"Mass - 6:00" BIT,
	Priest BIT,
	Sister BIT,
	Brother BIT
);
CREATE TABLE "Switchboard Items" (
	SwitchboardID INTEGER,
	ItemNumber SMALLINT DEFAULT 0,
	ItemText VARCHAR(255),
	Command SMALLINT,
	Argument VARCHAR(255)
);
CREATE TABLE ZipCode (
	City VARCHAR(50),
	State VARCHAR(50),
	Zip VARCHAR(50),
	ID INTEGER
);
;
